### ISSUE TITLE
garage-deploy is slow

### ISSUE THREAD

**Issue by Bubu** [advancedtelematic/aktualizr#1015]
When using garage-deploy to cross-deploy an image to another garage account this usually takes between 45 and 60 minutes on a fast internet connection.

I'm really not sure where the bottle-neck is, but this seems far slower then the initial garage-pushes, which usually complete in well under 5 minutes.

**Comment by patrickvacek** [comment]
@Bubu For the most part, I think this is fundamental to how the two tools work and how they are generally used. Both rely on OSTree to determine what objects are "new" and thus require uploading. Any parent objects of a commit that are already found on the destination server are not re-uploaded, and all of their children are assumed to already be present as well. garage-push is usually fast because from one run to the next, there are usually not great changes and thus not many objects need to be uploaded. Additionally, the source repository is on your local hard drive.

For garage-deploy, the mechanics are similar, but since it moves objects from one server to another, there are twice as many network operations: the objects first must get downloaded from the source repository and then uploaded to the destination repository. Furthermore, since garage-deploy is typically not used as often as garage-push, the number of missing objects in the destination repository is likely to be much greater.

While those issues are unlikely to be something we can improve, there is a third issue that might be something we could look into. There are four types of OSTree objects, and we currently do not have a good way to determine which one an object is, and when we look for objects in a repository, we have to try all four versions until we find something. When the repo is local, this is rather quick, but when it is remote, we have to do this with HEAD requests. While cheap, they are not free. Also, if the object is not found, we try again in order to rule out network flakiness. Perhaps there is some way to be smarter about this process.

Do you see other parts of the process that you think are inefficient or could be improved in some way? We have not recently thoroughly reviewed the code with speed in mind, so it is possible that there are still other gains to be found.

**Comment by patrickvacek** [comment]
I would also expect using garage-push with the local repo intact from the last bitbake to indeed be much faster than garage-deploy. However, 1 minutes vs 45 seems like a huge difference, so maybe there is something we are overlooking or doing unnecessarily inefficiently.

**Comment by patrickvacek** [comment]
@Bubu I've done some work to improve garage-deploy in several ways over the past few weeks (see https://github.com/advancedtelematic/aktualizr/pull/1020). I think you should see a substantial improvement in speed, but I'm curious how it looks for you. Can you test out the latest master? If it would be helpful for us to make a new release or update aktualizr in a branch of meta-updater, we can do that, too.

**Comment by patrickvacek** [comment]
@Bubu I've released a new version of garage-deploy if you are interested: https://github.com/advancedtelematic/aktualizr/releases/tag/2019.1

I'm curious if the new version helps out and thus if we can close this ticket.

**Comment by Bubu** [comment]
It's a lot faster now, thanks. Took about 3 minutes to cross-deploy an image. :+1: 

/close
