### ISSUE TITLE
What's the best way to document the DockerAppp PackageManager

### ISSUE THREAD

**Issue by doanac** [advancedtelematic/aktualizr#1396]
I know there's been a bit of churn lately as you guys have been doing lots of work on documentation. One thing that's lacking technically is an explanation of the DockerAppPackageManger. I've recently [blogged](https://foundries.io/insights/2019/09/23/docker-app/) about this and was wondering the best way for me to get something like this merged into this repo. I'm guessing I should avoid the usual `src/libaktualizr/package_manager/README.md`. So I'm wondering if I should try something like the Doxygen route or doing something here: https://github.com/advancedtelematic/aktualizr/tree/master/docs/ota-client-guide/modules/ROOT/pages?

Let me know how I can help.

**Comment by merltron** [comment]
Hi Andy, we use Antora to publish the docs - here's [an article on the dir structure](https://docs.antora.org/antora/2.1/component-structure/) to give you a bit of context.

I assume the content that you plan to add is for aktualizr contributors? (rather than end users) In which case, you just need to create a new adoc file, the reference it in the [navigation file](https://github.com/advancedtelematic/aktualizr/blob/master/docs/ota-client-guide/modules/ROOT/nav.adoc) under the section called "For contributors".

Create a PR for your changes and request it to be merged into the latest docs branch "2019.8-docs" (rather than "master"). 

@patrickvacek anything else to add?
