### ISSUE TITLE
Is "If-not-modified-since" possible?

### ISSUE THREAD

**Issue by doanac** [advancedtelematic/aktualizr#1446]
I've been thinking a little on how to make aktualizr/tuf-reposerver be a little less chatty. Currently you have to do 4 round trips to the server for root.json, timestamp.json, snapshot.json, and targets.json. I was wondering if there was a way to limit the total number of requests or just return `HTTP_304 Not Modified` by using the [`if-not-modified-since`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Modified-Since) header to limit the total amount of data transferred? I have a feeling the answer is "_no, it would create a security issue covered by TUF_". I just wanted to confirm.

**Comment by doanac** [comment]
Another thing on this topic. I *think* we could add something like this to aktualizr:
~~~
 curl_easy_setopt(curl, CURLOPT_ACCEPT_ENCODING, "gzip");
~~~

And then something like this to the nginx proxy for the tuf-reposerver:
~~~
      gzip             on;
      gzip_comp_level  7;
      gzip_types       application/json;
~~~

and transfer a lot less data. My un-scientific test against a targets.json I have was:
~~~
 * targets.json  - 86924 bytes
 * targs.json.gz - 12266 bytes (~14% the size of the original)
~~~

And agents not specifying that header will still work properly and get the traditional un-compressed value.

**Comment by patrickvacek** [comment]
> Currently you have to do 4 round trips to the server for root.json, timestamp.json, snapshot.json, and targets.json.

We've actually just been discussing this! TUF doesn't require downloading the next metadata file in the flow if the previous one has not indicated that something changed, and we realized that Uptane is not written to accommodate that (https://github.com/uptane/uptane-standard/issues/147). Aktualizr does not take that shortcut, but it could, so we will probably work on improving that soon.

> I was wondering if there was a way to limit the total number of requests or just return `HTTP_304 Not Modified` by using the [`if-not-modified-since`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Modified-Since) header to limit the total amount of data transferred?

Interesting idea, but shouldn't be necessary if we do the above correctly. Actually, maybe it'd still be useful for the root.json, since you always have to download that. @simao @koshelev how does that sound to you?

> Another thing on this topic. I _think_ we could add something like this to aktualizr:
> 
> ```
>  curl_easy_setopt(curl, CURLOPT_ACCEPT_ENCODING, "gzip");
> ```

That also sounds like a reasonable thing to do, but I'll defer to my colleagues on the backend side as to what they think of it. As long as curl is automatically handling the decompression, I don't think it should affect the Uptane logic.

**Comment by patrickvacek** [comment]
Also @zabbal do you have any concerns with the `HTTP 304 Not Modified` idea (presumably just for the root metadata)?

**Comment by simao** [comment]
> > Currently you have to do 4 round trips to the server for root.json, timestamp.json, snapshot.json, and targets.json.
> 
> We've actually just been discussing this! TUF doesn't require downloading the next metadata file in the flow if the previous one has not indicated that something changed, and we realized that Uptane is not written to accommodate that ([uptane/uptane-standard#147](https://github.com/uptane/uptane-standard/issues/147)). Aktualizr does not take that shortcut, but it could, so we will probably work on improving that soon.
> 
> > I was wondering if there was a way to limit the total number of requests or just return `HTTP_304 Not Modified` by using the [`if-not-modified-since`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Modified-Since) header to limit the total amount of data transferred?
> 
> Interesting idea, but shouldn't be necessary if we do the above correctly. Actually, maybe it'd still be useful for the root.json, since you always have to download that. @simao @koshelev how does that sound to you?

From the BE side yes, I think this could be something we could implement, as long as we don't see any security implication.

> 
> > Another thing on this topic. I _think_ we could add something like this to aktualizr:
> > ```
> >  curl_easy_setopt(curl, CURLOPT_ACCEPT_ENCODING, "gzip");
> > ```
> 

I think we should avoid compressing tls traffic, see http://www.breachattack.com/ for example, but @zabbal  would know more about this.

I think we could compress it before tls, but we'd have to test how this would work. I think we could probably do something about this, but not entirely sure it is as simple as adding a few directives to nginx.

> That also sounds like a reasonable thing to do, but I'll defer to my colleagues on the backend side as to what they think of it. As long as curl is automatically handling the decompression, I don't think it should affect the Uptane logic.

**Comment by patrickvacek** [comment]
> I think we should avoid compressing tls traffic, see http://www.breachattack.com/ for example, but @zabbal would know more about this.

Oof. Don't know how I missed that one. However, my initial dive into that hasn't convinced me that we'd be vulnerable to it. We'd definitely need to do some more research to be confident before enabling that, though.

**Comment by mike-sul** [comment]
These both features are quite ubiquitous in CDN space and most of HTTP/S servers, including nginx, support  them out of the box.
http://nginx.org/en/docs/http/ngx_http_gzip_module.html
http://nginx.org/en/docs/http/ngx_http_core_module.html#if_modified_since

**Comment by mike-sul** [comment]
`GET /director/root.json HTTP/1.1
Host: c7ce59cd-5754-4f56-b093-72735156db70.device-gateway.ota.api.here.com
User-Agent: Aktualizr/2019.9-67-g1c2f495e
Accept-Encoding: gzip
Content-Type: application/json
Accept: */*
If-Modified-Since: Tue, 11 Dec 2020 10:10:24 GMT

< HTTP/1.1 200 OK
< X-B3-SpanId: 1bb97a373e2273b4
< Date: Thu, 14 Nov 2019 11:31:50 GMT
< X-B3-Sampled: true
< Server: akka-http/10.1.8
< x-ats-version: director/0.8.0-30-ge3aca46
< Content-Type: application/json
< X-B3-ParentSpanId: 8bac3b8c022aeb3a
< X-B3-TraceId: 8bac3b8c022aeb3a
< content-encoding: gzip
< content-length: 1925`

**Comment by zabbal** [comment]
I'm kinda on a fence about it. On the one hand neither BREACH/CRIME (potentially enabled by compression) nor cache poisoning (potentially enabled by if-not-modified-since) will affect us immediately as we do not reflect user's data back and we do not use caches.

However if at some point in the future we will make seemingly unrelated changes we might become vulnerable because our threat model assumptions have changed without us noticing. This is something which could be easily overlooked.

In a bit more details.

Regarding compression, I'd rather avoid using it unless we have something more tangible than desire to make smth "a little less chatty". I mean what's the exact problem we're trying to solve by this? Not enough bw? Number of requests? Response latency? How does it look like in numbers - we use X Gbps, Y requests/sec, Z usec response time etc. And what should new numbers look like - how do we know we've actually solved it?

Even If using gzip save us 86%, we're still talking about 70Kb - does this number actualy makes a difference? Under which conditions?

Btw, I'm not even sure if compression is not already enabled in nginx depending on clients' request simply because it's default config - something worth looking into.

Regarding if-not-modified-since we should really think about how much trust do we put into time source we have on a client. The Uptane itself takes this into account - see https://github.com/uptane/deployment-considerations/blob/master/repositories.md#secure-source-of-time for example, so we might argue that we can just rely on the client's time anyway. However, by using if-not-modified-since we make time critical at 2 protocol levels at once: the signatures check might fail with the wrong time and download of root.json might fail due to wrong time at the level below Uptane. Overall it makes reasoning about our implementation more complex compared to current situation where underlying http is just a dumb pipe which works regardless of client time skew. Btw, do correct me if I'm wrong and any part of this is noncense.

Hence, I similarly would like to quantify actual benefits we could gain from this increase in complexity: is it some problem which affects us already? Is it smth we'll hit once we scale up to N users/machines? What other options do we have to fix it?

Overall, I'd say let's take some numbers, implement uptane/uptane-standard#147 improvements, than get the numbers again and see if we still have a problem we've got to fix.

**Comment by patrickvacek** [comment]
> Regarding compression, I'd rather avoid using it unless we have something more tangible than desire to make smth "a little less chatty". I mean what's the exact problem we're trying to solve by this? Not enough bw? Number of requests? Response latency? How does it look like in numbers - we use X Gbps, Y requests/sec, Z usec response time etc. And what should new numbers look like - how do we know we've actually solved it?

These are valid questions, but the general answer is that less is basically always better. We know many users are concerned about bandwidth usage. Some have hard data limits per month, and either way, every kB counts, and all the more so the larger a fleet is. We haven't always made this a top priority, but it's likely to be a bigger topic soon.

**Comment by doanac** [comment]
> Regarding compression, I'd rather avoid using it unless we have something more tangible than desire to make smth "a little less chatty".

We have a customer that's going to have devices checking in via LTE. So 86% is huge.

As per the BREACH/CRIME attack. I agree we should take that seriously. However, I'm talking about *response compression* not TLS compression. I *think* these are 2 [different things](https://blog.qualys.com/ssllabs/2012/09/14/crime-information-leakage-attack-against-ssltls). According to the "How Bad Is It" section:

>  *"TLS supports DEFLATE compression (not to be confused with HTTP response compression, which is very popular, but not vulnerable to CRIME)"*

**Comment by zabbal** [comment]
Sure, it's 2 different attacks, or more accurate, 2 variants of the same attack. CRIME is against TLS-level compression while BREACH is against HTTP-level compression. It can be implemented securely but it's not as easy as "flip the switch to get more bw" unfortunately. Hence I think we first should check all possible options and see which get most benefits while taking increase of complexity into account. And before that we should have accurate way to measure the gains.

**Comment by doanac** [comment]
I think we can close this after Patrick's change.
