### ISSUE TITLE
Config file ordering seems confusing

### ISSUE THREAD

**Issue by doanac** [advancedtelematic/aktualizr#1637]
We just hit something that seems unexpected when it comes to the order that toml files get added to the Config object.  We set our config directories to:
~~~
std::vector<boost::filesystem::path> config_dirs_ = {
 "/usr/lib/sota/conf.d", 
 "/var/sota/sota.toml",
 "/etc/sota/conf.d/"
};
~~~

Today I created a file, `/etc/sota/conf.d/50-pacman-override.toml`. I expected this to override values that were set in sota.toml. However, I discovered this wasn't the case. The config file logic puts *all* the config files into a `std::map` which happens to sort them. This meant `sota.toml` was lexicographically after my `50-pacman-override.toml` file and my "overrides" are actually the thing that got overridden.

I put together a trivial patch shown below. However, I found it breaks the config file testing. This leads me to believe your approach is intentional. Is this correct? This doesn't feel like how Unix config files normally get resolved, but you also don't normally have multiple conf.d directories.

So - possibly subjective, but would you be open to the patch below, or should I just carry that as an out-of-tree patch?

~~~
diff --git a/src/libaktualizr/utilities/config_utils.h b/src/libaktualizr/utilities/config_utils.h
index 4bc78cd95..7f8cbf100 100644
--- a/src/libaktualizr/utilities/config_utils.h
+++ b/src/libaktualizr/utilities/config_utils.h
@@ -138,22 +138,18 @@ class BaseConfig {
 
  protected:
   void updateFromDirs(const std::vector<boost::filesystem::path>& configs) {
-    std::map<std::string, boost::filesystem::path> configs_map;
     for (const auto& config : configs) {
       if (!boost::filesystem::exists(config)) {
         continue;
       }
       if (boost::filesystem::is_directory(config)) {
         for (const auto& config_file : Utils::getDirEntriesByExt(config, ".toml")) {
-          configs_map[config_file.filename().string()] = config_file;
+          updateFromToml(config_file);
         }
       } else {
-        configs_map[config.filename().string()] = config;
+        updateFromToml(config);
       }
     }
-    for (const auto& config_file : configs_map) {
-      updateFromToml(config_file.second);
-    }
   }
~~~

**Comment by ricardosalveti** [comment]
It's normal for software to have default configs at /usr/lib/foo and user defined ones at /etc/foo (and usually they are parsed while loaded, so you know a certain config option set in a fragment in /etc will always have higher priority over one set in /usr).

**Comment by patrickvacek** [comment]
Unfortunately, the behavior you are seeing is what I would expect based on https://docs.ota.here.com/ota-client/latest/aktualizr-config-options.html#_how_toml_files_are_processed. It is intentional that the files are sorted lexicographically before parsing. We expect the config files to be prefixed with a numeric priority, but your `sota.toml` doesn't have that, and it gets processed last. `/var/sota/sota.toml` is a relic of the past for us, and we don't treat it specially.

**Comment by ricardosalveti** [comment]
But even without var/sota/sota.toml we might experience a few issues from the way I see:
1 - Files under /usr/lib/sota/conf.d and /etc/sota/conf.d/ with the same filename but different content might result in configs not being parsed at all (and the user would have to know that it is not creating a file in etc that is not conflicting with one present at usr).
2 - Configs at /etc/sota/conf.d/ might end up being ignored if it has a lower number index prepending the file name with a similar one available at /usr/lib/sota/conf.d, since what matters in the end is the order of the file names, and not the original location.

**Comment by patrickvacek** [comment]
Perhaps it is worth restating that this config parsing system was intended to match the way systemd's configuration is handled. It's not exact, since the use case is slightly different, but the principles are similar. I think what is most confusing, though, is that you can manually pass in config directories and paths and it's not entirely obvious how they are treated.

I think this isn't the most straightforward system, but it is quite flexible, which was the goal. I'm hesitant to change it, though, because it could be a subtle change that might break things for people in unexpected ways without them noticing.

>  1 - Files under /usr/lib/sota/conf.d and /etc/sota/conf.d/ with the same filename but different content might result in configs not being parsed at all (and the user would have to know that it is not creating a file in etc that is conflicting with one present at usr).

Yes, that is correct and intended. The point is that `/usr/lib` is provided by the image while `/etc` can be manually edited.

>  2 - Configs at /etc/sota/conf.d/ might end up being ignored if it has a lower number index prepending the file name with a similar one available at /usr/lib/sota/conf.d

Yes, that is correct and intended.

> since what matters in the end is the order of the file names, and not the original location.

Both aspects matter. The directories are search in order of preference for files, with can result in some files being ignored in favor of later ones found with the same name, and the resulting list is parsed in alphabetic order, meaning settings in some can be overruled by others.

**Comment by ricardosalveti** [comment]
> I think this isn't the most straightforward system, but it is quite flexible, which was the goal. I'm hesitant to change it, though, because it could be a subtle change that might break things for people in unexpected ways without them noticing.

Right, while confusing in a way, changing this behavior will indeed cause unexpected side effects.
