### ISSUE TITLE
Add tests based on uptane-test-vectors

### ISSUE THREAD

**Issue by cajun-rat** [advancedtelematic/aktualizr#182]
It is important that we can verify the security behaviour of Aktualizr against the UPTANE/ spec. There is a project here: https://github.com/heartsucker/uptane-test-vectors which contains a set of test cases (aka vectors) for UPTANE.

Some of these tests require ed25519 signatures, so we will need to skip them until we add ed25519 signature support to Aktualizr.

I suggest that we simply copy the https://github.com/heartsucker/uptane-test-vectors/tree/master/vectors directory into aktualizr/tests rather than try and use git submodules or anything similar. Our C++ test can then read vector-meta.json and execute the test cases from that.

**Comment by heartsucker** [comment]
Btw, you might actually want https://github.com/heartsucker/uptane-test-vectors since that has the mix of director + repo.

Also, I think the default encoding for signatures is different than what we use at ATS (hex vs. base64). There are some CLI flags that will let you run the `generate.py` script in an ATS compatible way. You can run it once and dump the output to the directory and everything should work.

**Comment by cajun-rat** [comment]
Good point. I'd missed that.  Yes, we should be using uptane-test-vectors

**Comment by cajun-rat** [comment]
Done
